imports:
    - { resource: config.yml }


framework:
    assets:
        packages:
            images:
                # The base url to use for the 'images' asset package, can be ammended to make use of a cdn
                # base_urls: 'http://cdn.mycdn.com'

#config database parameters
doctrine:
    dbal:
        default_connection: hotstatus_mysql
        connections:
            hotstatus_mysql:
                driver: pdo_mysql
                host: '%hotstatus_mysql_prod_host%'
                port: '%hotstatus_mysql_prod_port%'
                dbname: '%hotstatus_mysql_prod_dbname%'
                user: '%hotstatus_mysql_prod_user%'
                password: '%hotstatus_mysql_prod_password%'
                charset: UTF8MB4

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
